name: myenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - xarray
  - netCDF4
  - dask
  - matplotlib
  - seaborn
  - scikit-learn
  - scipy
  - jupyter
  - nc-time-axis
  - pip
  - pip:
    - xgboost
    - lightgbm
    - tensorflow
    - certifi
